import Foundation

/// Rich demo inventory so the app is immediately actionable in Simulator.
struct SampleCatalogProvider: ListingProvider {
    let source: ListingSource = .carGurus

    func fetchListings(models: [TeslaModel]) async throws -> [VehicleListing] {
        SampleCatalog.all.filter { models.contains($0.model) }
    }
}

enum SampleCatalog {
    static let all: [VehicleListing] = {
        let cal = Calendar.current
        func daysAgo(_ n: Int) -> Date {
            cal.date(byAdding: .hour, value: -n, to: Date()) ?? Date()
        }

        let raw: [VehicleListing] = [
            VehicleListing(
                id: "y-great-1",
                vin: "5YJYGDEE8PF123456",
                model: .modelY,
                trim: "Long Range",
                year: 2023,
                price: 32_900,
                mileage: 18_400,
                title: "2023 Tesla Model Y Long Range",
                location: "Austin, TX",
                source: .carGurus,
                listingURL: URL(string: "https://www.cargurus.com/Cars/l-Used-Tesla-Model-Y")!,
                imageURL: URL(string: "https://images.unsplash.com/photo-1617788138017-80ad40651399?w=400"),
                exteriorColor: "Pearl White",
                interiorColor: "Black",
                autopilot: .fsd,
                hardwareVersion: .hw3,
                hasFSDCapableHardware: true,
                accidentCount: 0,
                ownerCount: 1,
                repairHistory: [],
                listedAt: daysAgo(2),
                dealerName: "Tesla Austin",
                dealScore: 0,
                dealGrade: .fair,
                scoreBreakdown: nil
            ),
            VehicleListing(
                id: "y-hw4-great",
                vin: "7SAYGDEE1RA654321",
                model: .modelY,
                trim: "Long Range",
                year: 2024,
                price: 36_500,
                mileage: 9_200,
                title: "2024 Tesla Model Y Long Range AWD",
                location: "San Jose, CA",
                source: .teslaUsed,
                listingURL: URL(string: "https://www.tesla.com/inventory/used/my")!,
                imageURL: URL(string: "https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=400"),
                exteriorColor: "Stealth Grey",
                interiorColor: "White",
                autopilot: .autopilot,
                hardwareVersion: .hw4,
                hasFSDCapableHardware: true,
                accidentCount: 0,
                ownerCount: 1,
                repairHistory: [],
                listedAt: daysAgo(1),
                dealerName: "Tesla Used",
                dealScore: 0,
                dealGrade: .fair,
                scoreBreakdown: nil
            ),
            VehicleListing(
                id: "3-good-1",
                vin: "5YJ3E1EA5PF789012",
                model: .model3,
                trim: "Performance",
                year: 2022,
                price: 28_750,
                mileage: 31_000,
                title: "2022 Tesla Model 3 Performance",
                location: "Denver, CO",
                source: .autotrader,
                listingURL: URL(string: "https://www.autotrader.com/cars-for-sale/tesla/model-3")!,
                imageURL: URL(string: "https://images.unsplash.com/photo-1536700503339-1e4b06520771?w=400"),
                exteriorColor: "Red Multi-Coat",
                interiorColor: "Black",
                autopilot: .enhancedAutopilot,
                hardwareVersion: .hw3,
                hasFSDCapableHardware: true,
                accidentCount: 0,
                ownerCount: 1,
                repairHistory: [
                    RepairRecord(date: daysAgo(400), description: "Front bumper respray", costEstimate: 900, severity: .minor)
                ],
                listedAt: daysAgo(5),
                dealerName: "Mile High EV",
                dealScore: 0,
                dealGrade: .fair,
                scoreBreakdown: nil
            ),
            VehicleListing(
                id: "s-fair-1",
                vin: "5YJSA1E51PF345678",
                model: .modelS,
                trim: "Plaid",
                year: 2021,
                price: 58_900,
                mileage: 42_000,
                title: "2021 Tesla Model S Plaid",
                location: "Miami, FL",
                source: .carsCom,
                listingURL: URL(string: "https://www.cars.com/shopping/results/?makes[]=tesla&models[]=tesla-s")!,
                imageURL: URL(string: "https://images.unsplash.com/photo-1617704548623-340376564e68?w=400"),
                exteriorColor: "Solid Black",
                interiorColor: "Cream",
                autopilot: .fsd,
                hardwareVersion: .hw3,
                hasFSDCapableHardware: true,
                accidentCount: 1,
                ownerCount: 2,
                repairHistory: [
                    RepairRecord(date: daysAgo(200), description: "Rear quarter panel repair", costEstimate: 4200, severity: .major)
                ],
                listedAt: daysAgo(8),
                dealerName: "Coastal Motors",
                dealScore: 0,
                dealGrade: .fair,
                scoreBreakdown: nil
            ),
            VehicleListing(
                id: "x-bad-1",
                vin: "7SAXCBE59NF901234",
                model: .modelX,
                trim: "Long Range",
                year: 2022,
                price: 72_000,
                mileage: 55_000,
                title: "2022 Tesla Model X Long Range",
                location: "Chicago, IL",
                source: .facebookMarketplace,
                listingURL: URL(string: "https://www.facebook.com/marketplace/search/?query=Tesla%20Model%20X")!,
                imageURL: URL(string: "https://images.unsplash.com/photo-1620891549027-942fdc95b18d?w=400"),
                exteriorColor: "Deep Blue",
                interiorColor: "Black",
                autopilot: .autopilot,
                hardwareVersion: .hw3,
                hasFSDCapableHardware: true,
                accidentCount: 2,
                ownerCount: 3,
                repairHistory: [
                    RepairRecord(date: daysAgo(100), description: "Falcon wing door actuator", costEstimate: 2800, severity: .moderate),
                    RepairRecord(date: daysAgo(300), description: "Front collision repair", costEstimate: 7500, severity: .structural)
                ],
                listedAt: daysAgo(12),
                dealerName: "Private Seller",
                dealScore: 0,
                dealGrade: .fair,
                scoreBreakdown: nil
            ),
            VehicleListing(
                id: "ct-great-1",
                vin: "7G2CEHED5RA112233",
                model: .cybertruck,
                trim: "AWD",
                year: 2024,
                price: 68_500,
                mileage: 4_800,
                title: "2024 Tesla Cybertruck AWD",
                location: "Phoenix, AZ",
                source: .trueCar,
                listingURL: URL(string: "https://www.truecar.com/used-cars-for-sale/listings/tesla/cybertruck/")!,
                imageURL: URL(string: "https://images.unsplash.com/photo-1698778458728-4c5a0c8b0b0a?w=400"),
                exteriorColor: "Stainless",
                interiorColor: "Black",
                autopilot: .fsd,
                hardwareVersion: .hw4,
                hasFSDCapableHardware: true,
                accidentCount: 0,
                ownerCount: 1,
                repairHistory: [],
                listedAt: daysAgo(3),
                dealerName: "Desert EV Exchange",
                dealScore: 0,
                dealGrade: .fair,
                scoreBreakdown: nil
            ),
            VehicleListing(
                id: "y-good-fb",
                vin: "5YJYGDEE2MF556677",
                model: .modelY,
                trim: "RWD",
                year: 2021,
                price: 24_900,
                mileage: 48_200,
                title: "2021 Tesla Model Y",
                location: "Seattle, WA",
                source: .facebookMarketplace,
                listingURL: URL(string: "https://www.facebook.com/marketplace/search/?query=Tesla%20Model%20Y")!,
                imageURL: URL(string: "https://images.unsplash.com/photo-1571987502227-9231b837d03c?w=400"),
                exteriorColor: "Midnight Silver",
                interiorColor: "Black",
                autopilot: .autopilot,
                hardwareVersion: .hw3,
                hasFSDCapableHardware: true,
                accidentCount: 0,
                ownerCount: 2,
                repairHistory: [],
                listedAt: daysAgo(4),
                dealerName: "Private Seller",
                dealScore: 0,
                dealGrade: .fair,
                scoreBreakdown: nil
            ),
            VehicleListing(
                id: "3-hw4-2024",
                vin: "5YJ3E1EB0RF889900",
                model: .model3,
                trim: "Long Range Highland",
                year: 2024,
                price: 34_200,
                mileage: 6_100,
                title: "2024 Tesla Model 3 Long Range",
                location: "Portland, OR",
                source: .edmunds,
                listingURL: URL(string: "https://www.edmunds.com/tesla/model-3/")!,
                imageURL: URL(string: "https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=400"),
                exteriorColor: "Ultra Red",
                interiorColor: "Black",
                autopilot: .fsd,
                hardwareVersion: .hw4,
                hasFSDCapableHardware: true,
                accidentCount: 0,
                ownerCount: 1,
                repairHistory: [],
                listedAt: daysAgo(0),
                dealerName: "Pacific Tesla Specialists",
                dealScore: 0,
                dealGrade: .fair,
                scoreBreakdown: nil
            ),
            VehicleListing(
                id: "s-hw4-good",
                vin: "5YJSA1E66RF445566",
                model: .modelS,
                trim: "Plaid",
                year: 2023,
                price: 69_900,
                mileage: 14_000,
                title: "2023 Tesla Model S Plaid",
                location: "Los Angeles, CA",
                source: .carGurus,
                listingURL: URL(string: "https://www.cargurus.com/Cars/l-Used-Tesla-Model-S")!,
                imageURL: URL(string: "https://images.unsplash.com/photo-1617704548623-340376564e68?w=400"),
                exteriorColor: "Pearl White",
                interiorColor: "Black",
                autopilot: .fsd,
                hardwareVersion: .hw4,
                hasFSDCapableHardware: true,
                accidentCount: 0,
                ownerCount: 1,
                repairHistory: [],
                listedAt: daysAgo(6),
                dealerName: "LA Autohaus",
                dealScore: 0,
                dealGrade: .fair,
                scoreBreakdown: nil
            ),
            VehicleListing(
                id: "x-great-low",
                vin: "7SAXCBE51PF778899",
                model: .modelX,
                trim: "Plaid",
                year: 2023,
                price: 64_500,
                mileage: 11_500,
                title: "2023 Tesla Model X Plaid",
                location: "Dallas, TX",
                source: .craigslist,
                listingURL: URL(string: "https://dallas.craigslist.org/search/cta?query=Tesla+Model+X")!,
                imageURL: URL(string: "https://images.unsplash.com/photo-1620891549027-942fdc95b18d?w=400"),
                exteriorColor: "Quicksilver",
                interiorColor: "White",
                autopilot: .fsd,
                hardwareVersion: .hw4,
                hasFSDCapableHardware: true,
                accidentCount: 0,
                ownerCount: 1,
                repairHistory: [],
                listedAt: daysAgo(1),
                dealerName: "Private Seller",
                dealScore: 0,
                dealGrade: .fair,
                scoreBreakdown: nil
            ),
            VehicleListing(
                id: "ct-fair",
                vin: "7G2CEHED8RA998877",
                model: .cybertruck,
                trim: "Cyberbeast",
                year: 2024,
                price: 99_000,
                mileage: 2_200,
                title: "2024 Tesla Cybertruck Cyberbeast",
                location: "Las Vegas, NV",
                source: .bringATrailer,
                listingURL: URL(string: "https://bringatrailer.com/tesla/?s=Cybertruck")!,
                imageURL: URL(string: "https://images.unsplash.com/photo-1698778458728-4c5a0c8b0b0a?w=400"),
                exteriorColor: "Stainless",
                interiorColor: "Black",
                autopilot: .fsd,
                hardwareVersion: .hw4,
                hasFSDCapableHardware: true,
                accidentCount: 0,
                ownerCount: 1,
                repairHistory: [],
                listedAt: daysAgo(7),
                dealerName: "BaT Auction",
                dealScore: 0,
                dealGrade: .fair,
                scoreBreakdown: nil
            ),
            VehicleListing(
                id: "y-bad-miles",
                vin: "5YJYGDEE3LF334455",
                model: .modelY,
                trim: "Long Range",
                year: 2020,
                price: 29_500,
                mileage: 112_000,
                title: "2020 Tesla Model Y Long Range",
                location: "Atlanta, GA",
                source: .carfax,
                listingURL: URL(string: "https://www.carfax.com/Used-Tesla-Model-Y_w113")!,
                imageURL: URL(string: "https://images.unsplash.com/photo-1617788138017-80ad40651399?w=400"),
                exteriorColor: "Blue",
                interiorColor: "Black",
                autopilot: .autopilot,
                hardwareVersion: .hw3,
                hasFSDCapableHardware: true,
                accidentCount: 1,
                ownerCount: 3,
                repairHistory: [
                    RepairRecord(date: daysAgo(500), description: "Battery coolant repair", costEstimate: 1500, severity: .moderate)
                ],
                listedAt: daysAgo(10),
                dealerName: "Southern Auto",
                dealScore: 0,
                dealGrade: .fair,
                scoreBreakdown: nil
            ),
        ]
        return raw
    }()
}
